// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kaeltebus_backend.Infrastructure.Database;

#nullable disable

namespace kaeltebus_backend.Application.Infrastructure.Database.Migrations
{
    [DbContext(typeof(KbContext))]
    [Migration("20240923210129_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("kaeltebus_backend.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<int>("ApproxAge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2094),
                            ApproxAge = 45,
                            Gender = 0,
                            IsDeleted = false,
                            Name = "Martin",
                            Remarks = ""
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2099),
                            ApproxAge = 40,
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Martina",
                            Remarks = ""
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2102),
                            ApproxAge = 30,
                            IsDeleted = false,
                            Name = "Tim",
                            Remarks = ""
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(1899),
                            IsDeleted = false,
                            RegistrationNumber = "UL-RK1013"
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoodId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("GoodId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LocationId");

                    b.ToTable("Distributions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 9, 13, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 5,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(2024, 9, 13, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 6,
                            IsDeleted = false,
                            LocationId = 3,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(2024, 9, 13, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 6,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 4,
                            AddOn = new DateTime(2024, 9, 13, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            AddOn = new DateTime(2024, 9, 13, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 6,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            AddOn = new DateTime(2024, 9, 13, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            AddOn = new DateTime(2024, 9, 14, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 5,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 8,
                            AddOn = new DateTime(2024, 9, 14, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            AddOn = new DateTime(2024, 9, 14, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 2,
                            IsDeleted = false,
                            LocationId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            AddOn = new DateTime(2024, 9, 14, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 6,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 11,
                            AddOn = new DateTime(2024, 9, 14, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 7,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 12,
                            AddOn = new DateTime(2024, 9, 14, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 13,
                            AddOn = new DateTime(2024, 9, 14, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 14,
                            AddOn = new DateTime(2024, 9, 15, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 6,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 15,
                            AddOn = new DateTime(2024, 9, 15, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 16,
                            AddOn = new DateTime(2024, 9, 15, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 17,
                            AddOn = new DateTime(2024, 9, 15, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 18,
                            AddOn = new DateTime(2024, 9, 15, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 6,
                            IsDeleted = false,
                            LocationId = 5,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 19,
                            AddOn = new DateTime(2024, 9, 15, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 3,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 20,
                            AddOn = new DateTime(2024, 9, 15, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 21,
                            AddOn = new DateTime(2024, 9, 15, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 3,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 22,
                            AddOn = new DateTime(2024, 9, 16, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 5,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 23,
                            AddOn = new DateTime(2024, 9, 16, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 24,
                            AddOn = new DateTime(2024, 9, 16, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 25,
                            AddOn = new DateTime(2024, 9, 16, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 2,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 26,
                            AddOn = new DateTime(2024, 9, 16, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 27,
                            AddOn = new DateTime(2024, 9, 16, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 7,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 28,
                            AddOn = new DateTime(2024, 9, 17, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 29,
                            AddOn = new DateTime(2024, 9, 17, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 7,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 30,
                            AddOn = new DateTime(2024, 9, 17, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 5,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 31,
                            AddOn = new DateTime(2024, 9, 17, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 5,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 32,
                            AddOn = new DateTime(2024, 9, 18, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 33,
                            AddOn = new DateTime(2024, 9, 18, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 2,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 34,
                            AddOn = new DateTime(2024, 9, 18, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 3,
                            IsDeleted = false,
                            LocationId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 35,
                            AddOn = new DateTime(2024, 9, 18, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 5,
                            IsDeleted = false,
                            LocationId = 3,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 36,
                            AddOn = new DateTime(2024, 9, 18, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 37,
                            AddOn = new DateTime(2024, 9, 18, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 5,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 38,
                            AddOn = new DateTime(2024, 9, 18, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 7,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 39,
                            AddOn = new DateTime(2024, 9, 18, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 6,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 40,
                            AddOn = new DateTime(2024, 9, 18, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 7,
                            IsDeleted = false,
                            LocationId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 41,
                            AddOn = new DateTime(2024, 9, 19, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 6,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 42,
                            AddOn = new DateTime(2024, 9, 19, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 7,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 43,
                            AddOn = new DateTime(2024, 9, 19, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 44,
                            AddOn = new DateTime(2024, 9, 19, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 2,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 45,
                            AddOn = new DateTime(2024, 9, 19, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 46,
                            AddOn = new DateTime(2024, 9, 19, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 47,
                            AddOn = new DateTime(2024, 9, 19, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 48,
                            AddOn = new DateTime(2024, 9, 19, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 3,
                            IsDeleted = false,
                            LocationId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 49,
                            AddOn = new DateTime(2024, 9, 19, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 6,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 50,
                            AddOn = new DateTime(2024, 9, 20, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 5,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 51,
                            AddOn = new DateTime(2024, 9, 20, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 52,
                            AddOn = new DateTime(2024, 9, 20, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 3,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 53,
                            AddOn = new DateTime(2024, 9, 21, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 7,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 54,
                            AddOn = new DateTime(2024, 9, 21, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 55,
                            AddOn = new DateTime(2024, 9, 21, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 3,
                            IsDeleted = false,
                            LocationId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 56,
                            AddOn = new DateTime(2024, 9, 21, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 5,
                            IsDeleted = false,
                            LocationId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 57,
                            AddOn = new DateTime(2024, 9, 22, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 58,
                            AddOn = new DateTime(2024, 9, 22, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            LocationId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 59,
                            AddOn = new DateTime(2024, 9, 22, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 5,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 60,
                            AddOn = new DateTime(2024, 9, 22, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 6,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 61,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 1,
                            DeviceId = 1,
                            GoodId = 3,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 62,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            LocationId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 63,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 3,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 64,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 3,
                            DeviceId = 1,
                            GoodId = 6,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 65,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2226),
                            ClientId = 2,
                            DeviceId = 1,
                            GoodId = 7,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoodType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Goods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 2,
                            IsDeleted = false,
                            Name = "Suppe",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 2,
                            IsDeleted = false,
                            Name = "Kaffee",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 2,
                            IsDeleted = false,
                            Name = "Tee",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 4,
                            AddOn = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 1,
                            IsDeleted = false,
                            Name = "Decke",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 5,
                            AddOn = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 1,
                            IsDeleted = false,
                            Name = "Socken",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 6,
                            AddOn = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 0,
                            IsDeleted = false,
                            Name = "Tempos",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 7,
                            AddOn = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 0,
                            IsDeleted = false,
                            Name = "Deo",
                            Tags = "[]"
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2130),
                            IsDeleted = false,
                            Name = "Alter Friedhof"
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2186),
                            IsDeleted = false,
                            Name = "Bahnhof"
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2190),
                            IsDeleted = false,
                            Name = "Neue Mitte"
                        },
                        new
                        {
                            Id = 4,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2192),
                            IsDeleted = false,
                            Name = "Hirschstraße"
                        },
                        new
                        {
                            Id = 5,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2195),
                            IsDeleted = false,
                            Name = "Schillerstraße"
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(2059),
                            Date = new DateOnly(2024, 9, 23),
                            DeviceId = 1,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.ShiftVolunteer", b =>
                {
                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShiftId", "VolunteerId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("ShiftVolunteers");
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDriver")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Firstname", "Lastname")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(1850),
                            Firstname = "Luka",
                            Gender = 0,
                            IsDeleted = false,
                            IsDriver = false,
                            Lastname = "Weis",
                            Remarks = ""
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(1855),
                            Firstname = "Peter",
                            Gender = 0,
                            IsDeleted = false,
                            IsDriver = true,
                            Lastname = "Pan",
                            Remarks = ""
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(1858),
                            Firstname = "Max",
                            Gender = 0,
                            IsDeleted = false,
                            IsDriver = false,
                            Lastname = "Mustermann",
                            Remarks = ""
                        },
                        new
                        {
                            Id = 4,
                            AddOn = new DateTime(2024, 9, 23, 23, 1, 28, 849, DateTimeKind.Local).AddTicks(1861),
                            Firstname = "Corinna",
                            Gender = 1,
                            IsDeleted = false,
                            IsDriver = true,
                            Lastname = "Braun",
                            Remarks = ""
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Distribution", b =>
                {
                    b.HasOne("kaeltebus_backend.Models.Client", "Client")
                        .WithMany("Distributions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kaeltebus_backend.Models.Device", "Device")
                        .WithMany("Distributions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kaeltebus_backend.Models.Good", "Good")
                        .WithMany("Distributions")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kaeltebus_backend.Models.Location", "Location")
                        .WithMany("Distributions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Device");

                    b.Navigation("Good");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Shift", b =>
                {
                    b.HasOne("kaeltebus_backend.Models.Device", "Device")
                        .WithMany("Shifts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("kaeltebus_backend.Models.ShiftVolunteer", b =>
                {
                    b.HasOne("kaeltebus_backend.Models.Shift", "Shift")
                        .WithMany("ShiftVolunteers")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kaeltebus_backend.Models.Volunteer", "Volunteer")
                        .WithMany("ShiftVolunteers")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Client", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Device", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Good", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Location", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Shift", b =>
                {
                    b.Navigation("ShiftVolunteers");
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Volunteer", b =>
                {
                    b.Navigation("ShiftVolunteers");
                });
#pragma warning restore 612, 618
        }
    }
}
