// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kaeltebus_backend.Infrastructure.Database;

#nullable disable

namespace kaeltebus_backend.Application.Infrastructure.Database.Migrations
{
    [DbContext(typeof(KbContext))]
    partial class KbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("kaeltebus_backend.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<int>("ApproxAge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 9, 4, 22, 50, 50, 165, DateTimeKind.Local).AddTicks(1453),
                            ApproxAge = 45,
                            Gender = 0,
                            IsDeleted = false,
                            Name = "Martin",
                            Remarks = ""
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(2024, 9, 4, 22, 50, 50, 165, DateTimeKind.Local).AddTicks(1458),
                            ApproxAge = 40,
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Martina",
                            Remarks = ""
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(2024, 9, 4, 22, 50, 50, 165, DateTimeKind.Local).AddTicks(1461),
                            ApproxAge = 30,
                            Gender = 0,
                            IsDeleted = false,
                            Name = "Tim",
                            Remarks = ""
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoodId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("GoodId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ShiftId");

                    b.ToTable("Distributions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 9, 4, 22, 50, 50, 165, DateTimeKind.Local).AddTicks(1507),
                            ClientId = 1,
                            GoodId = 1,
                            IsDeleted = false,
                            Quantity = 1,
                            ShiftId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(2024, 9, 4, 22, 50, 50, 165, DateTimeKind.Local).AddTicks(1511),
                            ClientId = 1,
                            GoodId = 2,
                            IsDeleted = false,
                            Quantity = 2,
                            ShiftId = 1
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(2024, 9, 4, 22, 50, 50, 165, DateTimeKind.Local).AddTicks(1514),
                            ClientId = 1,
                            GoodId = 4,
                            IsDeleted = false,
                            Quantity = 1,
                            ShiftId = 1
                        },
                        new
                        {
                            Id = 4,
                            AddOn = new DateTime(2024, 9, 4, 22, 50, 50, 165, DateTimeKind.Local).AddTicks(1517),
                            ClientId = 2,
                            GoodId = 2,
                            IsDeleted = false,
                            Quantity = 1,
                            ShiftId = 1
                        },
                        new
                        {
                            Id = 5,
                            AddOn = new DateTime(2024, 9, 4, 22, 50, 50, 165, DateTimeKind.Local).AddTicks(1520),
                            ClientId = 3,
                            GoodId = 1,
                            IsDeleted = false,
                            Quantity = 1,
                            ShiftId = 1
                        },
                        new
                        {
                            Id = 6,
                            AddOn = new DateTime(2024, 9, 4, 22, 50, 50, 165, DateTimeKind.Local).AddTicks(1523),
                            ClientId = 3,
                            GoodId = 3,
                            IsDeleted = false,
                            Quantity = 2,
                            ShiftId = 1
                        },
                        new
                        {
                            Id = 7,
                            AddOn = new DateTime(2024, 9, 4, 22, 50, 50, 165, DateTimeKind.Local).AddTicks(1526),
                            ClientId = 3,
                            GoodId = 7,
                            IsDeleted = false,
                            Quantity = 1,
                            ShiftId = 1
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoodType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Goods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 2,
                            IsDeleted = false,
                            Name = "Suppe",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 2,
                            IsDeleted = false,
                            Name = "Kaffee",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 2,
                            IsDeleted = false,
                            Name = "Tee",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 4,
                            AddOn = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 1,
                            IsDeleted = false,
                            Name = "Decke",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 5,
                            AddOn = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 1,
                            IsDeleted = false,
                            Name = "Socken",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 6,
                            AddOn = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 0,
                            IsDeleted = false,
                            Name = "Tempos",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 7,
                            AddOn = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 0,
                            IsDeleted = false,
                            Name = "Deo",
                            Tags = "[]"
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 9, 4, 22, 50, 50, 165, DateTimeKind.Local).AddTicks(1415),
                            Date = new DateOnly(2024, 9, 4),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.ShiftVolunteer", b =>
                {
                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShiftId", "VolunteerId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("ShiftVolunteers");
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDriver")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Firstname", "Lastname")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Luka",
                            Gender = 0,
                            IsDeleted = false,
                            IsDriver = false,
                            Lastname = "Weis",
                            Remarks = ""
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Peter",
                            Gender = 0,
                            IsDeleted = false,
                            IsDriver = false,
                            Lastname = "Pan",
                            Remarks = ""
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Max",
                            Gender = 0,
                            IsDeleted = false,
                            IsDriver = false,
                            Lastname = "Mustermann",
                            Remarks = ""
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Distribution", b =>
                {
                    b.HasOne("kaeltebus_backend.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kaeltebus_backend.Models.Good", "Good")
                        .WithMany()
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kaeltebus_backend.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Good");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("kaeltebus_backend.Models.ShiftVolunteer", b =>
                {
                    b.HasOne("kaeltebus_backend.Models.Shift", "Shift")
                        .WithMany("ShiftVolunteers")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kaeltebus_backend.Models.Volunteer", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Shift", b =>
                {
                    b.Navigation("ShiftVolunteers");
                });
#pragma warning restore 612, 618
        }
    }
}
