// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using kaeltehilfe_backend.Infrastructure.Database;

#nullable disable

namespace kaeltehilfe_backend.Application.Infrastructure.Database.Migrations
{
    [DbContext(typeof(KbContext))]
    partial class KbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("kaeltehilfe_backend.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<long?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Busses");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<int>("ApproxAge")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<Point>("GeoLocation")
                        .HasColumnType("POINT")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<int>("GoodId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddOn");

                    b.HasIndex("BusId");

                    b.HasIndex("ClientId");

                    b.HasIndex("GoodId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LocationId");

                    b.ToTable("Distributions");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<long?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoodType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TwoWeekThreshold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<long?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Login", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Username");

                    b.HasAlternateKey("IdentityProviderId");

                    b.ToTable("Logins");

                    b.HasDiscriminator<int>("Role");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.LoginCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<long?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LoginUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ValidFrom")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValidTo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LoginUsername");

                    b.ToTable("LoginCertificates");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.ShiftVolunteer", b =>
                {
                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShiftId", "VolunteerId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("ShiftVolunteers");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<long?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDriver")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Firstname", "Lastname")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.AdminLogin", b =>
                {
                    b.HasBaseType("kaeltehilfe_backend.Models.Login");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.OperatorLogin", b =>
                {
                    b.HasBaseType("kaeltehilfe_backend.Models.Login");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Distribution", b =>
                {
                    b.HasOne("kaeltehilfe_backend.Models.Bus", "Bus")
                        .WithMany("Distributions")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kaeltehilfe_backend.Models.Client", "Client")
                        .WithMany("Distributions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kaeltehilfe_backend.Models.Good", "Good")
                        .WithMany("Distributions")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kaeltehilfe_backend.Models.Location", "Location")
                        .WithMany("Distributions")
                        .HasForeignKey("LocationId");

                    b.Navigation("Bus");

                    b.Navigation("Client");

                    b.Navigation("Good");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.LoginCertificate", b =>
                {
                    b.HasOne("kaeltehilfe_backend.Models.Login", "Login")
                        .WithMany("LoginCertificates")
                        .HasForeignKey("LoginUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Shift", b =>
                {
                    b.HasOne("kaeltehilfe_backend.Models.Bus", "Bus")
                        .WithMany("Shifts")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.ShiftVolunteer", b =>
                {
                    b.HasOne("kaeltehilfe_backend.Models.Shift", "Shift")
                        .WithMany("ShiftVolunteers")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kaeltehilfe_backend.Models.Volunteer", "Volunteer")
                        .WithMany("ShiftVolunteers")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Bus", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Client", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Good", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Location", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Login", b =>
                {
                    b.Navigation("LoginCertificates");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Shift", b =>
                {
                    b.Navigation("ShiftVolunteers");
                });

            modelBuilder.Entity("kaeltehilfe_backend.Models.Volunteer", b =>
                {
                    b.Navigation("ShiftVolunteers");
                });
#pragma warning restore 612, 618
        }
    }
}
