version: '3.8'
services:
  certs-init:
    build:
      context: ./certs-init/image
      dockerfile: Dockerfile
    environment:
      PASSWORD: ${ROOT_CERT_PASSWORD}
      EXPORT_CRT_PATH: /app/output/crt/rootCa.crt
      EXPORT_PFX_PATH: /app/output/pfx/rootCa.pfx
      CA_NAME: KaeltehilfeRootCA
    volumes:
      - ./certs/root-crt:/app/output/crt
      - ./certs/root-pfx:/app/output/pfx
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  
  keycloak:
    build:
      context: ./keycloak/image
      dockerfile: dockerfile
    command: start-dev --health-enabled=true
    ports:
      - '8050:8080'
      - '8051:9000'
    environment:
      KC_HOSTNAME: 'localhost'
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: 'true'
      KC_PROXY_HEADERS: 'xforwarded'
      KC_HTTP_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_RELATIVE_PATH: /
      KC_PROXY_ADDRESS_FORWARDING: 'true'
      KC_SPI_X509CERT_LOOKUP_PROVIDER: 'nginx'
      KC_SPI_X509CERT_LOOKUP_NGINX_SSL_CLIENT_CERT: 'X-Client-Cert'
      KC_TRUSTSTORE_PATHS: '/certs/root/rootCa.crt'
    volumes:
        - ./keycloak/data:/opt/keycloak/data
        - ./keycloak/themes:/opt/keycloak/providers
        - ./certs/root-crt:/certs/root
        - ./certs/crl:/opt/keycloak/conf/crl
    depends_on:
      certs-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9000/health/ready | grep -q '\"status\": \"UP\"'"]
      interval: 10s
      timeout: 5s
      retries: 20
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  keycloak-init:
    build:
      context: ./keycloak-init
      dockerfile: dockerfile
    environment:
      REALM_NAME: kaeltehilfe
      REALM_REQUIRE_SSL: NONE
      KC_BASE_URL: http://keycloak:8080
      KC_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      APP_URL: http://localhost:5173
      APP_ADMIN_USERNAME: Max.Mustermann@gmail.com
      APP_ADMIN_FIRSTNAME: Max
      APP_ADMIN_LASTNAME: Mustermann
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      MACHINE_CLIENT_SECRET: ${KC_CLIENT_SECRET}
      USER_CLIENT_ID: ${KC_USER_CLIENT_ID}
    depends_on:
      keycloak:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  pgosm-db:
    image: postgis/postgis:18-3.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGIS_ADMIN}
      POSTGRES_PASSWORD: ${POSTGIS_PASSWORD}
      POSTGRES_DB: ${POSTGIS_DB}
    volumes:
      - ./pgosm-db/postgresql:/var/lib/postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  pgosm-init:
    build: 
      context: ./pgosm-init/image
      dockerfile: Dockerfile
    volumes:
      - ./pgosm-init/input:/app/input
    depends_on:
      pgosm-db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: pgosm-db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ${POSTGIS_DB}
      POSTGRES_USER: ${POSTGIS_ADMIN}
      PGUSER: ${POSTGIS_ADMIN}
      POSTGRES_PASSWORD: ${POSTGIS_PASSWORD}
      PGOSM_RAM: 8
      # PGOSM_REGION: europe
      # PGOSM_SUBREGION: germany
      # PGOSM_INPUT_FILE: /app/input/germany-latest.osm.pbf
      PGOSM_REGION: europe/germany
      PGOSM_SUBREGION: baden-wuerttemberg/tuebingen-regbez
      PGOSM_INPUT_FILE: /app/input/tuebingen-regbez-latest.osm.pbf
    logging:
      driver: "json-file"
      options:
        max-size: "50m"