FROM golang:1.25 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/kaeltehilfe-geo ./cmd/api

FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /app/kaeltehilfe-geo /kaeltehilfe-geo
EXPOSE 8083
ENTRYPOINT ["/kaeltehilfe-geo"]
