// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kaeltebus_backend.Infrastructure.Database;

#nullable disable

namespace kaeltebus_backend.Infrastructure.Database.Migrations
{
    [DbContext(typeof(KbContext))]
    partial class KbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("ShiftVolunteer", b =>
                {
                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShiftId", "VolunteerId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("ShiftVolunteer", (string)null);

                    b.HasData(
                        new
                        {
                            ShiftId = 1,
                            VolunteerId = 1
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<int>("ApproxAge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 7, 9, 22, 53, 8, 565, DateTimeKind.Local).AddTicks(2875),
                            ApproxAge = 45,
                            Gender = 0,
                            Name = "Martin"
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(2024, 7, 9, 22, 53, 8, 565, DateTimeKind.Local).AddTicks(2881),
                            ApproxAge = 40,
                            Gender = 1,
                            Name = "Martina"
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(2024, 7, 9, 22, 53, 8, 565, DateTimeKind.Local).AddTicks(2885),
                            ApproxAge = 30,
                            Gender = 0,
                            Name = "Tim"
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("GoodId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Distributions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 7, 9, 22, 53, 8, 565, DateTimeKind.Local).AddTicks(2937),
                            ClientId = 1,
                            GoodId = 1,
                            Quantity = 1,
                            ShiftId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(2024, 7, 9, 22, 53, 8, 565, DateTimeKind.Local).AddTicks(2943),
                            ClientId = 1,
                            GoodId = 2,
                            Quantity = 2,
                            ShiftId = 1
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(2024, 7, 9, 22, 53, 8, 565, DateTimeKind.Local).AddTicks(2947),
                            ClientId = 1,
                            GoodId = 4,
                            Quantity = 1,
                            ShiftId = 1
                        },
                        new
                        {
                            Id = 4,
                            AddOn = new DateTime(2024, 7, 9, 22, 53, 8, 565, DateTimeKind.Local).AddTicks(2950),
                            ClientId = 2,
                            GoodId = 2,
                            Quantity = 1,
                            ShiftId = 1
                        },
                        new
                        {
                            Id = 5,
                            AddOn = new DateTime(2024, 7, 9, 22, 53, 8, 565, DateTimeKind.Local).AddTicks(2954),
                            ClientId = 3,
                            GoodId = 1,
                            Quantity = 1,
                            ShiftId = 1
                        },
                        new
                        {
                            Id = 6,
                            AddOn = new DateTime(2024, 7, 9, 22, 53, 8, 565, DateTimeKind.Local).AddTicks(2956),
                            ClientId = 3,
                            GoodId = 3,
                            Quantity = 2,
                            ShiftId = 1
                        },
                        new
                        {
                            Id = 7,
                            AddOn = new DateTime(2024, 7, 9, 22, 53, 8, 565, DateTimeKind.Local).AddTicks(2959),
                            ClientId = 3,
                            GoodId = 7,
                            Quantity = 1,
                            ShiftId = 1
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoodType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Goods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 7, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 2,
                            Name = "Suppe",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(2024, 7, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 2,
                            Name = "Kaffee",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(2024, 7, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 2,
                            Name = "Tee",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 4,
                            AddOn = new DateTime(2024, 7, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 1,
                            Name = "Decke",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 5,
                            AddOn = new DateTime(2024, 7, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 1,
                            Name = "Socken",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 6,
                            AddOn = new DateTime(2024, 7, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 0,
                            Name = "Tempos",
                            Tags = "[]"
                        },
                        new
                        {
                            Id = 7,
                            AddOn = new DateTime(2024, 7, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "",
                            GoodType = 0,
                            Name = "Deo",
                            Tags = "[]"
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2024, 7, 9, 22, 53, 8, 565, DateTimeKind.Local).AddTicks(2798),
                            Date = new DateOnly(2024, 7, 9)
                        });
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<DateTime?>("ChangeOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDriver")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Firstname", "Lastname");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Luka",
                            Gender = 0,
                            IsDriver = false,
                            Lastname = "Weis"
                        },
                        new
                        {
                            Id = 2,
                            AddOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Peter",
                            Gender = 0,
                            IsDriver = false,
                            Lastname = "Pan"
                        },
                        new
                        {
                            Id = 3,
                            AddOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Max",
                            Gender = 0,
                            IsDriver = false,
                            Lastname = "Mustermann"
                        });
                });

            modelBuilder.Entity("ShiftVolunteer", b =>
                {
                    b.HasOne("kaeltebus_backend.Models.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("kaeltebus_backend.Models.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });

            modelBuilder.Entity("kaeltebus_backend.Models.Distribution", b =>
                {
                    b.HasOne("kaeltebus_backend.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("kaeltebus_backend.Models.Good", "Good")
                        .WithMany()
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("kaeltebus_backend.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Good");

                    b.Navigation("Shift");
                });
#pragma warning restore 612, 618
        }
    }
}
